dist: bionic
language: csharp
mono: none

os:
  - linux
  - osx

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - NUGET_XMLDOC_MODE=skip

branches:
  only:
    - master

cache:
  directories:
    - /home/travis/.nuget/packages

script:
  - ./build.sh
