os: Visual Studio 2017
version: 1.0.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
  NUGET_API_KEY:
    secure: 6MzbzEs4YdJKS67Gio5gEO8mNKmwfC4UHTCmECZ1KOutI6ndm4vAECazmVNB6an7

branches:
  only:
    - master

build_script:
  - ps: .\Build.ps1 -RestorePackages

after_build:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "artifacts\code-coverage.xml"

artifacts:
  - path: artifacts\*.nupkg

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off

deploy_script:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe  
  - ps: if ($env:APPVEYOR_REPO_TAG -ne "false") { ($artifacts.values | Where-Object {($_.path -like '*.nupkg') -and  !($_.path -like '*.symbols.nupkg')}) | foreach-object {nuget.exe push $_.path -Source https://www.nuget.org/api/v2/package -ApiKey $env:NUGET_API_KEY; if ($lastexitcode -ne 0) {throw}}}

#deploy:
#
#  - provider: NuGet
#    api_key:
#      secure: 6MzbzEs4YdJKS67Gio5gEO8mNKmwfC4UHTCmECZ1KOutI6ndm4vAECazmVNB6an7
#    artifact: /.*\.nupkg/
#    skip_symbols: false
#    on:
#      appveyor_repo_tag: true
#
